# Codecov 配置文件
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # 如果覆盖率下降超过 1%，则标记为失败
        target: auto
        threshold: 1%
        base: auto
        
    patch:
      default:
        # 新代码的覆盖率要求
        target: 80%
        threshold: 10%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

# 忽略某些文件的覆盖率
ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/tests/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/*.d.ts"